#!/usr/bin/env python3

import json
import locale
import sys

from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph, Spacer, Table, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

import emails
import reports

def load_data(filename):
    """Loads the contents of filename as a JSON file."""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data


def format_car(car):
    """Given a car dictionary, returns a nicely formatted name."""
    return "{} {} ({})".format(
        car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
    """Analyzes the data, looking for maximums.

    Returns a list of lines that summarize the information.
    """
    max_revenue = {"revenue": 0}
    max_sales = {"total_sales": 0}
    most_popular = {}
    for item in data:
        # Calculate the revenue generated by this model (price * total_sales)
        # We need to convert the price from "$1234.56" to 1234.56
        item_price = locale.atof(item["price"].strip("$"))
        item_revenue = item["total_sales"] * item_price
        if item_revenue > max_revenue["revenue"]:
            item["revenue"] = item_revenue
            max_revenue = item
        # TODO: also handle max sales
        # TODO: also handle most popular car_year
        if max_sales["total_sales"] < item["total_sales"]:
            max_sales = item

        if item["car"]["car_year"] in most_popular:
            most_popular[item["car"]["car_year"]] += item["total_sales"]
        else:
            most_popular[item["car"]["car_year"]] = item["total_sales"]
        
    most_popular_year = max(most_popular, key = most_popular.get)
    total_sales = most_popular[most_popular_year]
    summary = [
        "The {} generated the most revenue: ${}".format(
            format_car(max_revenue["car"]), max_revenue["revenue"]),
        "The {} had the most sales: {}".format(
            format_car(max_sales["car"]), max_sales["total_sales"]),
        "The most popular year was {} with {} sales.".format(
            most_popular_year, total_sales),
    ]
    return summary


def cars_dict_to_table(car_data):
    """Turns the data in car_data into a list of lists."""
    table_data = [["ID", "Car", "Price", "Total Sales"]]
    for item in car_data:
        table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
    return table_data



"""Process the JSON data and generate a full report out of it."""
data = load_data("car_sales.json")
summary = process_data(data)

# TODO: turn this into a PDF report
table_data = cars_dict_to_table(data)
filename = "/tmp/cars.pdf"
title = "Sales summary for last month"
additional_info = summary[0]+"<br/>"+summary[1]+"<br/>"+summary[2]
reports.generate(filename, title, additional_info, table_data)

# TODO: send the PDF report as an email attachment
sender = "automation@example.com"
recipient = "@example.com"
subject = 'Sales summary for last month'
body = summary[0]+"\n"+summary[1]+"\n"+summary[2]
message = emails.generate(sender, recipient, subject, body, filename)
emails.send(message)